### PR TITLE
feat: update jimp version

### PR DESCRIPTION
**Pull request by sj82516**
1. Update Jimp package version
2. Add package-lock.json
3. Fix eslint issue

I passed all test.  
This should be solved multiple issue 

1. https://github.com/preco21/merge-img/issues/15
`npm audit` would only report low priority issue.
2. https://github.com/preco21/merge-img/issues/6

### CODE REVIEW

**Comment by mathias22osterhagen22** [comment]
Please merge it asap

**Comment by preco21** [comment]
Hi, sorry for the late response.

I'm not quite sure if we can just upgrade it and go since I haven't been worked on this module for a long time.

**Comment by yuanchieh-cheng** [comment]
@preco21 Do you need more test case to approve the PR ? 
Maybe you could mention some test case scenario and I would help to write test cases.

**Comment by clementlecorre** [comment]
👍

**Comment by nflexfo** [comment]
:+1:

**Comment by mfranzke** [comment]
@preco21 & @alirezamirian: First of all thanks a lot for your software. Do you have the chance in approving this PR as it will fix in high severity bug in a subdependency of jimp-dependency?

**Comment by senpl** [comment]
@preco21 Why this PR can not be just merged ???

**Comment by senpl** [comment]
For this tired of waiting I created copy https://www.npmjs.com/package/merge-img-vwv only downside is that it has to be merge-img-vwv instead of merge-img . I just took this PR update lib and description. It works on my cases, if something is not work after lib update PR are welcomed.

**Comment by preco21** [comment]
Hi, my apologies for the late response. I missed the email notification and now I've just realized that this PR is still open.

I'm merging this PR anyway even if it's no longer relevant.

Please note that this project is no longer maintained.

I recommend you to use alternatives or pick up the simple algorithm from the library source then combine with the latest modules. Or, feel free to fork it.

Thanks.

**Pull request merged**
